---
- name: Update apt
  become: true
  apt:
    update_cache: yes
- name: add repo
  apt_repository:
    repo: ppa:openjdk-r/ppa
- name: install java
  apt:
    name: openjdk-7-jdk
    state: present
- name: Update-apt
  become: true
  apt:
    update_cache: yes
- name: download zookeeper
  get_url: url=http://www-eu.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz dest=/opt/
- name: extract zookeeper
  unarchive: src=/opt/zookeeper-3.4.6.tar.gz dest=/opt copy=no creates=/opt/zookeeper
- name: rename zookeeper dir
  command: mv /opt/zookeeper-3.4.6 /opt/zookeeper
- name: Set permissions to Zookeeper folder
  file: path=/opt/zookeeper/ owner=root group=root recurse=yes
- name: Create Zookeeper log directory
  file: path={{ zookeeper_log_dir }} state=directory
- name: Create Zookeeper conf directory
  file: path={{ zookeeper_conf_dir }} state=directory owner=root group=root mode=755
- name: create data directory
  file: path={{ zookeeper_data_dir }} state=directory
- name: creating config file
  template: src=zoo.cfg.j2 dest={{ zookeeper_conf_dir }}/zoo.cfg
- name: assigning id
  template: src=myid.j2 dest="{{ zookeeper_data_dir }}/myid"
- name: initialize
  command: bash /opt/zookeeper/bin/zkServer.sh start
- name: Make sure Zookeeper is running
  command: bash /opt/zookeeper/bin/zkServer.sh status
